### ISSUE TITLE
Improve exception handling

### ISSUE THREAD

**Issue by sylvanie85** [ai-cfia/nachet-backend#112]
We want to inform users when an error occurs during a request.

The backend needs to handle all errors and return them clearly for the frontend to use.

Acceptance Criteria :
- [x] every route handles unknown exceptions
- [x] each route handles custom exceptions that clearly indicate what has happened

**Comment by Francois-Werbrouck** [comment]
I like this issue. Do you plan on returning error numbers? Will you have a doc of all error type?
