### ISSUE TITLE
Retrieve inference after feedback

### ISSUE THREAD

**Issue by sylvanie85** [ai-cfia/nachet-backend#119]
## Context

When a user gives feedback, the inference is not updated on the front end view.

For example here is a picture of Ambrosia artemisiifolia but two of the seeds are classified as Ambrosia psilostachya so I want to give a wrong seed feedback.
![picture](https://github.com/user-attachments/assets/a993d703-3141-4371-aef2-fa964ad59c2a)
I submit the feedback
![picture](https://github.com/user-attachments/assets/36887aa5-87c5-4f4c-b8bb-c36ba0ea389a)
But the inference hasn't changed, the seed is still classified as a bad seed in the view.
![picture](https://github.com/user-attachments/assets/809824eb-d895-445e-b316-fcce7a1c11c8)

## Solution
A solution could be to send back the corrected inference after a feedback, the function already exist in the datastore so it would be easy

- [ ] send the inference as a response of a feedback request

**Comment by ChromaticPanic** [comment]
Yeah, great idea. We probably need some front-end modification as well, maybe turn the boxes green for verified inferences
