### ISSUE TITLE
Deploy nachet-backend application to GCP

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/nachet-backend#16]
Workflow for deeployment to GCP is needed currently nothing gets deployed

**Comment by rngadam** [comment]
nachet is misspelled and there's a typo in the description (and the typo in nachet has been transferred to the PR too).

**Comment by vivalareda** [comment]
> nachet is misspelled and there's a typo in the description (and the typo in nachet has been transferred to the PR too).

yeah like I said it's an old issue I don't make that mistake anymore really, as you have experienced with me when I have a lot of things in my mind I make a lot of stupid mistakes but since then I took the necessary steps to avoid this as much as possible, as for the PR I just tend to copy paste
