### ISSUE TITLE
Fix condition to check for None type

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/nachet-backend#18]

**Comment by vivalareda** [comment]
https://github.com/ai-cfia/nachet-backend/blob/d4bc5bcecec0e1cec09cb37f8cc02b6565b91a83/app.py#L28-L33

**Comment by issamansur** [comment]
Do I need to change `not endpoint_api_key` to `endpoint_api_key is not None` ?

**Comment by vivalareda** [comment]
an error message needs to be raised when the file type is none. When I tried to deploy, I got this error 
TypeError: expected string or bytes-like object, got 'NoneType' - needs to be handled
