### ISSUE TITLE
Storing Model Metadata

### ISSUE THREAD

**Issue by RussellJimmies** [ai-cfia/nachet-backend#22]
We want the user to be able to view the model's metadata, such as the number of seeds it has been trained to identify, and other pieces of information that might be useful to the user. 

We need to store such information in a JSON file somewhere that can be accessed via the backend. 

https://learn.microsoft.com/en-us/rest/api/azureml/

**Comment by rngadam** [comment]
@RussellJimmies document an example of the JSON to serve as specification and share with datascience group

**Comment by MaxenceGui** [comment]
Archives from project board on November 14

**Comment by MaxenceGui** [comment]
Archives from project board on November 14
