### ISSUE TITLE
nachet-backend lint-test failing 

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/nachet-backend#36]
Workflow to deploy was added to the repository which includes lint-test that are falling, I am not sure exactly was causes this but one of the issue seems to be that it's trying to iterate over an object which is not a list

Logs available here
https://github.com/ai-cfia/nachet-backend/actions/runs/7046229033/job/19177590933

**Comment by MaxenceGui** [comment]
Fixes by
* #53
