### ISSUE TITLE
Drawing "red box" error

### ISSUE THREAD

**Issue by TaranMeyer** [ai-cfia/nachet-backend#62]
**Description**
It looks like the model for segmenting out the individual seeds and drawing red boxes around them has an issue when the red boxes would overlap, due to the shape, proximity, or orientation of the seeds.

**Expected behavior**
A red box would be drawn around each seed, overlapping slightly due to the angled orientation of the seeds

**Actual Behavior**
Only a single box is visible, surrounding the first (leftmost, higher) seed. Both IDs appear to be attached to that box. When I rotate the seeds so that the red boxes can be drawn without them overlapping, they appear as expected.

**Supporting Images**
To better understand the issue, please add screenshots:
* **Results**: Include a screenshot of the interface showing the classification error or the issue as it appears in your environment.

![image](https://github.com/ai-cfia/nachet-model/assets/142623921/e7293963-0cda-4d06-a7b8-9559c4d789e1)
![image](https://github.com/ai-cfia/nachet-model/assets/142623921/6ceef78f-282a-4338-80de-ed3fc6ab281c)

* **Source Image**: Attach the actual picture or image used when you encountered the issue.
* 
![WIN_20240306_11_38_18_Pro](https://github.com/ai-cfia/nachet-model/assets/142623921/ec08c466-72ee-47a4-9bb5-8cd36042e7a2)
![WIN_20240306_11_44_38_Pro](https://github.com/ai-cfia/nachet-model/assets/142623921/e49893aa-8071-425d-a5ac-54999ad88524)

* **Microscope Settings**:  the microscope settings when the picture was taken.
![WIN_20240306_11_38_53_Pro](https://github.com/ai-cfia/nachet-model/assets/142623921/8da63b45-b585-454b-8ec0-c8dbcd97de32)

**Comment by rngadam** [comment]
@MaxenceGui can you provide an explanation as to why this is a backend issue rather than a model or frontend issue?

**Comment by MaxenceGui** [comment]
I want to investigate this in the backend before assuming it's a frontend issue because in the process_inference_request [line 93](https://github.com/ai-cfia/nachet-backend/blob/4985ad2df57833e286d1154f65acdc16305f4cff/model_inference/inference.py#L93) there a double for loop that decide if a box need to be hide if it's overlapping another one. If my assumption is wrong, I will transfer this issue to the frontend.
