### ISSUE TITLE
Increase content length for uploads

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/nachet-backend#64]
@amirardalan9473 flagged that he cannot upload a file with 43mb size. We initially thought it was related to the ingress controller that hosts the backend but looking at the logs from the backend we see that its the web server that is giving the issue. 

Screenshot from nachet-backend logs (thank you argoCD) : 
![image](https://github.com/ai-cfia/nachet-backend/assets/73133692/0f9c246f-3030-4239-bd37-76081d91cb41)
Looking at the code, I see we are using Quart as a web framework. Parsing default values i see that the limit for content is set as 16 mb : 
![image](https://github.com/ai-cfia/nachet-backend/assets/73133692/733e3c18-6871-4e58-a10a-990de20c31d8)
reference :
https://github.com/pallets/quart/blob/8a0cdd5a650c29d036dfec3000818b0e06ce3e0c/src/quart/config.py#L19

We would need to increase this value to at least 200mb by doing something like : 
```
from flask import Flask, request

app = Flask(__name__)

app.config['MAX_CONTENT_LENGTH'] = 200 * 1024 * 1024
```

**Comment by SonOfLope** [comment]
for testing with a file, simply ask Amir or me and we'll provide it.

**Comment by MaxenceGui** [comment]
> for testing with a file, simply ask Amir or me and we'll provide it.

@SonOfLope I would like to have a test file if you can provide one :)

**Comment by MaxenceGui** [comment]
> @amirardalan9473 flagged that he cannot upload a file with 43mb size. We initially thought it was related to the ingress controller that hosts the backend but looking at the logs from the backend we see that its the web server that is giving the issue.
> 
> Screenshot from nachet-backend logs (thank you argoCD) : ![image](https://private-user-images.githubusercontent.com/73133692/312195610-0f9c246f-3030-4239-bd37-76081d91cb41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjE4NDMsIm5iZiI6MTcxMDQyMTU0MywicGF0aCI6Ii83MzEzMzY5Mi8zMTIxOTU2MTAtMGY5YzI0NmYtMzAzMC00MjM5LWJkMzctNzYwODFkOTFjYjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEzMDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNTdhMzUwNDM1MDA0ZTU3NGQ1NTEyNzhjMWU1YzJmYmZjZGY4YjFjNGI5NDU2Y2ZhZTMxYTg1ZTlmYTRmM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.emQT3LkYHo0IKQyBDgI_qRIAu4pCkYPTBWcW9JwZPs4) Looking at the code, I see we are using Quart as a web framework. Parsing default values i see that the limit for content is set as 16 mb : ![image](https://private-user-images.githubusercontent.com/73133692/312195826-733e3c18-6871-4e58-a10a-990de20c31d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjE4NDMsIm5iZiI6MTcxMDQyMTU0MywicGF0aCI6Ii83MzEzMzY5Mi8zMTIxOTU4MjYtNzMzZTNjMTgtNjg3MS00ZTU4LWExMGEtOTkwZGUyMGMzMWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEzMDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNjQyMTg5YmU1NDIzMDY3ZjdmOTQzYjY0ZDc3Zjc5ZTE5NmFkMTE1Y2QzZDJiOTAxMDgyNjIxZmQ3OWU3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lJaaZQ-qsLsLyp7o1XyfBE8_ilhlQukBWhllcwVdSHI) reference : https://github.com/pallets/quart/blob/8a0cdd5a650c29d036dfec3000818b0e06ce3e0c/src/quart/config.py#L19
> 
> We would need to increase this value to at least 200mb by doing something like :
> 
> ```
> from flask import Flask, request
> 
> app = Flask(__name__)
> 
> app.config['MAX_CONTENT_LENGTH'] = 200 * 1024 * 1024
> ```

The assumption is right. I add this line:

```python
app.config["MAX_CONTENT_LENGTH"] = 200 * 1024 * 1024  # 200MB
```

The system will be able to process the picture. However, `tiff` image is not displayed by the frontend relating to
*  https://github.com/ai-cfia/nachet-frontend/issues/89

**Comment by rngadam** [comment]
related to #58
