### ISSUE TITLE
Change implementation of API endpoints to use nachet-datastore for storing images and images related metadata

### ISSUE THREAD

**Issue by MaxenceGui** [ai-cfia/nachet-backend#69]
### Issue Description :rocket:

With nachet-datastore currently in development, the backend will need to move from the Azure Blob Storage to store nachet-datastore for images and images metadata to nachet-datastore.

current:

```mermaid
sequenceDiagram
    nachet-frontend  ->> nachet-backend: REST
    nachet-backend ->> blob-storage: REST queries
```

desired:

```mermaid
sequenceDiagram
    nachet-frontend  ->> nachet-backend: REST
    nachet-backend ->> nachet-datastore: function calls
    nachet-datastore ->> ailab-db: postgresql queries
    nachet-datastore ->> blob-storage: REST queries
```

### Acceptance Criteria ✅ 

- nachet-datastore is used
- Every reference to Azure Data Storage is move to the backend
- The endpoint for pictures batch import is tested and working

### Tasks 🛠️ 

- [x] Move the azure-storage-api.py to nachet-datastore
- [x] Import nachet-datastore from GitHub directly
- [x] #85
- [x] #74

**Comment by rngadam** [comment]
@MaxenceGui let's discuss this in-person, the description needs some work.
