### ISSUE TITLE
Modify existing nachet-backend code to use datastore

### ISSUE THREAD

**Issue by Francois-Werbrouck** [ai-cfia/nachet-backend#85]
We need the Frontend to send data to the datastore. Therefore the backend needs to adapt its image upload process to use the datastore layer of Nachet

- [x] Changing the Classify request to use the datastore
- [x] Retrieve and send to the FE the list of seed from the Datastore
- [x] Retrieve the Pipelines names and data from the Datastore and send them to the FE

**Comment by sylvanie85** [comment]
Updated the doc about the inference request
Waiting for the datastore to be using the new tables names so I can test that I retrieve the seeds and send them back to the FE

**Comment by sylvanie85** [comment]
Pipelines should be retrieved, I'm waiting for the database to be populated so I can test @Francois-Werbrouck

**Comment by sylvanie85** [comment]
Related PR #90
